### ISSUE TITLE
00 - What's new in 1.0 kernel busy nuisance with New cell magics

### ISSUE THREAD

**Issue by pleabargain** [ipython/ipython-in-depth#5]
python 3.2
running ipython3 notebook 
latest GIT pull

In order to get New cell magics to run I have to close down the notebook and restart it. Having to restart the kernel to get new cell magics to work is undesirable behavior.

Initially I run the cells then I came to new cell magics %%html. 
kernel busy and stays busy.
the terminal displays no errors.
I shut down the kernel and then restart 00 - What's new in 1.0
THEN the new cell magics will work but I have to restart the kernel. I can reproduce this behavior.

Same for all new cell magics
%%html
%%latex
%%javascript

thank you

**Comment by Carreau** [comment]
Closing as inactive.
