### ISSUE TITLE
spaces in file names and spaces in links lead to broken markdown links in tutorial

### ISSUE THREAD

**Issue by RobertHa** [ipython/ipython-in-depth#56]
The [front page notebook]( ../../ipython-in-depth/tree/master/examples/Notebook/Index.ipynb) if accessed via clicking on the Python tutorial on the [jupyter try website](https://jupyter.org/try).
I assume it has to do with the spaces in the file names in the provided path. Some have them and the links apparently work in github's markdown but not in the markdown used by jupyter. A few links in the notebook substitute the spaces in the links with %20 and then they work.

This is extra annoying if you are visiting for the first time and have no clue how to fix the links temporarily to proceed. 
Also, who would put spaces into file names? This can lead to a lot of issues under some systems.

- [ ] fix file names
- [ ] fix broken links
- [ ] also there is a mistake at the end of [this](https://github.com/ipython/ipython-in-depth/blob/master/examples/Notebook/Notebook%20Basics.ipynb) part of the tutorial. You want to explain how to open a terminal but write one should click on **"Text File"**

**Comment by minrk** [comment]
closed by #59
